- hosts: webserver
  become: true
  tasks: 
  - name: installing httpd package
    yum: name=httpd state=present
    
  - name: starting the httpd service
    service: name=httpd state=started
  
  - name: copy the source file to /var/www/html
    copy: src=index.html dest=/var/www/html/index.html
